version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  currency:
    build: ./currency
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./currency:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  redis:
    image: redis:5-alpine

  celery-beat:
    build: ./currency
    command: celery -A currency beat -l info
    volumes:
      - ./currency:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - currency

  celery:
    build: ./currency
    restart: always
    command: celery worker --app=currency --loglevel=info
    volumes:
      - ./currency:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - currency
      - redis
      - db


  dashboard:
    build: ./currency
    restart: always
    command: flower -A currency --port=5555 --broker=redis://redis:6379/0 --broker_api=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./.env.dev
    depends_on:
      - currency
      - redis
      - celery






volumes:
  postgres_data:

