# Generated by Django 3.2.8 on 2021-10-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='Валюта')),
                ('value', models.FloatField(verbose_name='Стоимость')),
                ('timestamp', models.BigIntegerField(verbose_name='Временная метка')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
    ]
